### ISSUE TITLE
Allow passing queryClient in options instead of taking it from the context

### ISSUE THREAD

**Issue by dimfeld** [SvelteStack/svelte-query#12]
We have a legacy AngularJS 1.x web app which is being converted to Svelte over time, and would like to start using svelte-query here, both inside Svelte code and in some of the old Angular code too, and have them share the same QueryClient. 

The main issue I'm having is that the only way for the various functions to get the query client is through `useQueryClient`, which depends on Svelte context.

I think this could be solved fairly easily if the various functions that call `useQueryClient` were able to get the client from the `options` object. Something like `const client: QueryClient = options.queryClient ?? useQueryClient()`. The only place I've seen where some design decision would need to be made is with `useIsFetching`, which doesn't take an options object.

What do you think about a change like this? I'm happy to put together the PR if you're ok with it. Thanks!

**Comment by dimfeld** [comment]
Made the change (no tests yet) at https://github.com/dimfeld/svelte-query/tree/queryclient-in-options

**Comment by amen-souissi** [comment]
Hello @dimfeld and thank you for this issue :)

I think we should only have one QueryClient. With your proposal, we can define many QueryClient. the useQueryClient guarantees this unicity.

**Comment by dimfeld** [comment]
Yeah I sympathize with that. The problem is that doesn't work in any sort of microfrontend scenario or when using more than one frontend framework like we are while we transition over to Svelte. I can just use my fork though; the changes are small enough that it shouldn't be a hassle to maintain.

**Comment by dimfeld** [comment]
Just an update if anyone else comes to this issue. As of Svelte 3.37 context can be passed into component created with the runtime API, so an external QueryClient can be passed in when creating components.
