### ISSUE TITLE
How would I go about refetching a query if another query comes back changed?

### ISSUE THREAD

**Issue by saturnonearth** [SvelteStack/svelte-query#18]
Basically, I have a query that I want to go and check a timestamp, and if that timestamp has changed, I want to refetch or fetch the actual data I need. I want to do this to prevent repeatedly fetching large amounts of data. 

Is this possible? If so, how would I go about doing this? Thanks.

**Comment by amen-souissi** [comment]
Hello and thanks :)

Since query keys uniquely describe the data they are fetching, they should include any variables you use in your query function that change.
I think that the timestamp should be included in your queryKeys.
Please see this https://sveltequery.vercel.app/guides/query-keys

**Comment by saturnonearth** [comment]
Hi there, I figured it out, thanks!
