### ISSUE TITLE
What about `grpc-web` calls?

### ISSUE THREAD

**Issue by frederikhors** [SvelteStack/svelte-query#20]
What about `grpc-web` calls?

**Comment by amen-souissi** [comment]
Please see  https://github.com/tannerlinsley/react-query/issues/171

**Comment by frederikhors** [comment]
Why? They are talking about websocket calls, right?

I'm talking about simple documentation examples for unary calls.

**Comment by frederikhors** [comment]
This can be closed. I can PR in the future a guide.
