### ISSUE TITLE
SvelteKit integration

### ISSUE THREAD

**Issue by yussdev** [SvelteStack/svelte-query#39]
is there a way to integrate svelte-query with SvelteKit ?

**Comment by tradaonline** [comment]
Any update on this issue? I'm waiting for this too. Hope coming soon.

**Comment by benmccann** [comment]
`detect-node` 2.1.0 now has an ESM version. Can anyone who hit this issue check if it is now fixed?

**Comment by benmccann** [comment]
This should be considered fixed now that https://github.com/SvelteStack/svelte-query/pull/44 has been merged

**Comment by benmccann** [comment]
svelte-query 1.4.1 has been released and should be fully compatible with SvelteKit

**Comment by frederikhors** [comment]
@yussdev can you please close this?

**Comment by benmccann** [comment]
It looks like there's still a minor issue, but this can be closed in favor of https://github.com/SvelteStack/svelte-query/issues/45

**Comment by freddez** [comment]
Does someone have a working example with sveltekit ?
I always get this error :

```
ReferenceError: require is not defined
    at /node_modules/broadcast-channel/dist/es/method-chooser.js:19:20
```

**Comment by freddez** [comment]
> Does someone have a working example with sveltekit ?
> I always get this error :
> 
> ```
> ReferenceError: require is not defined
>     at /node_modules/broadcast-channel/dist/es/method-chooser.js:19:20
> ```

Sorry if it is the wrong channel, but I've fixed my issue by adding :

```
optimizeDeps: {include: ['broadcast-channel']},
```
in svelte.config.js (config.kit.vite.optimizeDeps)

**Comment by SomaticIT** [comment]
Hello,

A new version (v1.5.0) of this library has been published today.
This version makes broadcast-channel an optional dependency.
This should fix all problems with svelte-kit.

If you need to use the experimental `broadcastQueryClient`, you now need to install it manually (see: [broadcastQueryClient](https://github.com/SvelteStack/svelte-query/blob/main/docs/src/pages/plugins/broadcastQueryClient.md)).

If you still encounter issues with v1.5.0. Please open a new issue.

**Comment by lkj4** [comment]
how does it integrate with SvelteKit's `load` function which provides a super-powered `fetch`, does svelte-query deal with this and all other SvelteKit extras? Would love to see this in the readme right at the top btw.
