### ISSUE TITLE
Reactive Query Key Change Detection ?

### ISSUE THREAD

**Issue by PeufOne** [SvelteStack/svelte-query#43]
Hi,

I'm probably missing a detail but I can't use the reactivity of Svelte for queryKey provided to useQuery().

Here is a very basic example of a search box that is not working : 

```svelte
<script>
  import { useQuery } from "@sveltestack/svelte-query";
  import debounce from "debounce";

  let search = "";

  function getTest({ queryKey }) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(`Response for queryKey ${JSON.stringify(queryKey)}`);
      }, 500);
    });
  }

  const query = useQuery(["test", search], getTest);

  const handleSearch = debounce(event => {
    search = event.target.value;
  }, 200);
</script>

<input type="search" placeholder="Search" on:input={handleSearch}>
```

[See on codesanbox](https://codesandbox.io/s/trusting-tharp-68ohi?file=/Test.svelte)

NOTE: the same logic work perfectly with react-query

Thank for this awesome framwork 💚
...and sorry for my english (Google trad)

**Comment by frederikhors** [comment]
> Leaving aside the technical difficulties, the way forward would be.
> 
> ```svelte
>  $: query = useQuery(["test", search], getTest);
> ```

Aren't you re-creating again and again that query this way, @PeufOne?

**Comment by PeufOne** [comment]
Hi @frederikhors,

Yes, but if the cache and performance are preserved, why not? ...

Isn't that what happened with react-query?

I carried out the same small example to make a comparison:

- [Demo in Svelte](https://codesandbox.io/s/trusting-tharp-68ohi?file=/Test.svelte)
- [Demo in React](https://codesandbox.io/s/sad-boyd-61cm5?file=/src/Test.js)

I know Svelte doesn't work like React at all.
But I don't understand that we can't expect the same level of ease of use ...

One-line query handling is great on React.
While on Svelte, using setOptions is inconvenient and updateOptions unfortunately does not refresh the request.

Thank you for your attention.

**Comment by frederikhors** [comment]
> But I don't understand that we can't expect the same level of ease of use...
> One-line query handling is great on React.

I know, is very good.

> While on Svelte, using `setOptions` is inconvenient and `updateOptions` unfortunately does not refresh the request.

I think this is a bug, but we should wait for an @amen-souissi answer.

**Comment by frederikhors** [comment]
Another issue is if you try to use:

```ts
let queryOptions = {
  queryKey: ["test", search],
  queryFn,
  refetchOnWindowFocus: isVisible,
  enabled: isVisible
};
```

the query starts two times. It's a mess!
