### ISSUE TITLE
unsupported engine warning

### ISSUE THREAD

**Issue by JustinVoitel** [SvelteStack/svelte-query#8]
Hey awesome library so far. Iam just wondering why there is a "Unsupported engine" warning when installing with npm v7. Is there a reason why I should use yarn instead of npm ?  
![image](https://user-images.githubusercontent.com/30449535/107121117-ffbba900-6890-11eb-886e-18c5c1cdfbfc.png)

**Comment by mirkoschubert** [comment]
I had the same warnings. Just use the LTS version of node.
